
BackItems = {
    ["markedbills"] = {
        model="prop_money_bag_01",
        quantity=1,
        back_bone = 24818,
        x = -0.4,
        y = -0.15,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },

    ["meth"] = {
        model="hei_prop_pill_bag_01", 
        quantity=1,
        back_bone = 24818,
        x = -0.1,
        y = -0.15,
        z = 0.12,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
    
    ["weapon_smg"] = {
        model="w_sb_smg", 
        quantity=1,
        back_bone = 24818,
        x = 0.0,
        y = -0.15,
        z = -0.12,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_assaultrifle"] = {
        model="w_ar_assaultrifle",
        quantity=1,
        back_bone = 24818,
        x = 0.0,
        y = -0.15,
        z = -0.05,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },

    ["weapon_specialcarbine"] = {
        model="w_ar_specialcarbine", 
        quantity=1,
        back_bone = 24818,
        x = 0.0,
        y = -0.15,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_carbinerifle"] = {
        model="w_ar_carbinerifle", 
        quantity=1,
        back_bone = 24818,
        x = 0.0,
        y = -0.15,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_carbinerifle_mk2"] = {
        model="w_ar_carbineriflemk2", 
        quantity=1,
        back_bone = 24818,
        x = 0.0,
        y = -0.15,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_rpg"] = {
        model="w_lr_rpg", 
        quantity=1,
        back_bone = 24818,
        x = 0.2,
        y = -0.15,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 180.0,
        z_rotation = 180.0,
    },
    ["weapon_assaultrifle2"] = {
        model="w_ar_assaultrifle2", 
        quantity=1,
        back_bone = 24818,
        x = 0.0,
        y = -0.15,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["weapon_groza"] = {
        model="w_ar_groza",
        quantity=1,
        back_bone = 24818,
        x = 0.0,
        y = -0.15,
        z = 0.08,
        x_rotation = 0.0,
        y_rotation = -180.0,
        z_rotation = 180.0,
    },
    ["coke_brick"] = {
        model="bkr_prop_coke_cutblock_01", 
        quantity=1,
        back_bone = 24818,
        x = -0.20,
        y = -0.15,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 90.0,
    },
    ["weed_bud"] = {
        model="bkr_prop_weed_drying_01a", 
        quantity=1,
        back_bone = 24818,
        x = -0.20,
        y = -0.17,
        z = 0.0,
        x_rotation = 0.0,
        y_rotation = 90.0,
        z_rotation = 0.0,
    },
}
